
/********************************************************************************************
* Standalone Engine Simulator
* Aaron S. (Detonation) 2023
******************************
  DESCRIPTION
  ====================
  Simple Engine Crank/Cam Trigger Simulator

  This project is a personal learning experience and isn't for end-user use.
  It will contain bugs, efficiency issues and is generally incomplete.
  If you are looking for an engine simulator I recommend the Speeduino fork of Ardustim.
       https://github.com/speeduino/Ardu-Stim
********************************************************************************************/

/********************************************************************************************
Notes: This file is for generating arrays upon selection hopefully saving space.

These functions where generated by chatGPT to progress the idea. The goal is to create a template
that can be filled out with various variables so new trigger wheels can be later added easily.

********************************************************************************************/

#include <Arduino.h>
#include <stdlib.h>
#include "wheel_defs.h"
#include "wheel_gen.h"
#include "structures.h"

extern wheels Wheels[];
extern uint8_t currentPattern; // Currently selected pattern.

// Wrong
void generate_fourty_minus_one(unsigned char *arr)
{
    for (int i = 0; i < 7; i++)
    {
        for (int j = 0; j < 10; j++)
        {
            arr[i * 10 + j] = (j % 2 == 0) ? 0 : 1;
        }
    }
    for (int j = 0; j < 9; j++)
    {
        arr[70 + j] = (j % 2 == 0) ? 0 : 1;
    }
    arr[79] = 0;
}

void generate_dizzy_four_trigger_return(unsigned char *arr)
{
    for (int i = 0; i < 5; i++)
    {
        arr[i] = 0;
    }
    for (int i = 5; i < 9; i++)
    {
        arr[i] = 1;
    }
}

// Wrong
void generate_oddfire_vr(unsigned char *arr)
{
    arr[0] = 1;
    for (int i = 1; i < 9; i++)
    {
        arr[i] = 0;
    }
    arr[9] = 1;
    for (int i = 10; i < 24; i++)
    {
        arr[i] = 0;
    }
}

// Wrong
void generate_optispark_lt1(unsigned char *arr)
{
    for (int i = 0; i < 360; i++)
    {
        arr[i] = (i % 2) ? 1 : 0;
    }
    for (int i = 0; i < 8; i++)
    {
        arr[50 + i * 30] = 2;
        arr[50 + i * 30 + 1] = 3;
    }
}
